precondition(WallaaMokoGATT.authenticationCommand("Moko4321") == Data([0xEA,1,0x55,8,77,111,107,111,52,51,50,49]))
precondition(WallaaMokoGATT.authenticationCommand("") == nil)
precondition(WallaaMokoGATT.authenticationCommand("é") == nil)
precondition(WallaaMokoGATT.authenticationCommand(String(repeating:"a", count:17)) == nil)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x55,1,0xAA])) == true)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x55,1,0])) == false)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x41,1,0xAA])) == nil)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,2,6,1,3])) == 3)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,1,6,1,3])) == nil)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,2,6,2,3])) == nil)
precondition(!WallaaMokoGATT.shouldEmit(previous:nil,count:1,initialRead:false))
precondition(!WallaaMokoGATT.shouldEmit(previous:0,count:1,initialRead:true))
precondition(!WallaaMokoGATT.shouldEmit(previous:3,count:3,initialRead:false))
precondition(!WallaaMokoGATT.shouldEmit(previous:3,count:0,initialRead:false))
precondition(WallaaMokoGATT.shouldEmit(previous:0,count:1,initialRead:false))
precondition(WallaaMokoGATT.shouldEmit(previous:255,count:1,initialRead:false))
print("16 verifiche protocollo GATT superate")

assert(!WallaaMokoGATT.controlChannelsReady(["AA07"]))
assert(!WallaaMokoGATT.controlChannelsReady(["AA01","AA07"]))
assert(!WallaaMokoGATT.controlChannelsReady(["AA02","AA07"]))
assert(WallaaMokoGATT.controlChannelsReady(["aa01","aa02","aa07"]))
print("4 verifiche dei canali di autenticazione superate")
