precondition(WallaaMokoGATT.authenticationCommand("Moko4321") == Data([0xEA,1,0x55,8,77,111,107,111,52,51,50,49]))
precondition(WallaaMokoGATT.authenticationCommand("") == nil)
precondition(WallaaMokoGATT.authenticationCommand("é") == nil)
precondition(WallaaMokoGATT.authenticationCommand(String(repeating:"a", count:17)) == nil)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x55,1,0xAA])) == true)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x55,1,0])) == false)
precondition(WallaaMokoGATT.authenticationReply(Data([0xEB,1,0x41,1,0xAA])) == nil)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,2,6,1,3])) == 3)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,1,6,1,3])) == nil)
precondition(WallaaMokoGATT.connectionCount(Data([0xEB,2,6,2,3])) == nil)
precondition(!WallaaMokoGATT.shouldEmit(previous:nil,count:1,initialRead:false))
precondition(!WallaaMokoGATT.shouldEmit(previous:0,count:1,initialRead:true))
precondition(!WallaaMokoGATT.shouldEmit(previous:3,count:3,initialRead:false))
precondition(!WallaaMokoGATT.shouldEmit(previous:3,count:0,initialRead:false))
precondition(WallaaMokoGATT.shouldEmit(previous:0,count:1,initialRead:false))
precondition(WallaaMokoGATT.shouldEmit(previous:255,count:1,initialRead:false))
// Observed H1 packets: a new single press still reports 1 a minute later.
precondition(WallaaMokoGATT.shouldEmit(previous:1,count:1,initialRead:false,quietGap:59))
precondition(WallaaMokoGATT.shouldEmit(previous:1,count:1,initialRead:false,quietGap:2))
precondition(!WallaaMokoGATT.shouldEmit(previous:1,count:1,initialRead:false,quietGap:0.423))
precondition(WallaaMokoGATT.shouldEmit(previous:nil,count:1,initialRead:false,quietGap:10))
precondition(WallaaMokoGATT.shouldEmit(previous:1,count:5,initialRead:false,quietGap:0.3))
precondition(!WallaaMokoGATT.shouldEmit(previous:1,count:1,initialRead:true,quietGap:59))
print("16 verifiche protocollo GATT superate")

assert(!WallaaMokoGATT.controlChannelsReady(["AA07"]))
assert(!WallaaMokoGATT.controlChannelsReady(["AA01","AA07"]))
assert(!WallaaMokoGATT.controlChannelsReady(["AA02","AA07"]))
assert(WallaaMokoGATT.controlChannelsReady(["aa01","aa02","aa07"]))
print("4 verifiche dei canali di autenticazione superate")

assert(WallaaMokoGATT.shouldStartHandshake(connected:true,authenticated:false,phase:"restoring"))
assert(!WallaaMokoGATT.shouldStartHandshake(connected:true,authenticated:false,phase:"authenticating"))
assert(!WallaaMokoGATT.shouldStartHandshake(connected:true,authenticated:true,phase:"ready"))
print("3 verifiche del ripristino superate")

assert(WallaaMokoGATT.telemetryReply(Data([0xeb,0,0x62,1,100]),command:0x62)?["battery"] as? Int == 100)
assert(WallaaMokoGATT.telemetryReply(Data([0xeb,0,0x4a,2,0x0b,0xee]),command:0x4a)?["batteryVoltageMv"] as? Int == 3054)
assert(WallaaMokoGATT.telemetryReply(Data([0xeb,0,0x62,1,255]),command:0x62)?.isEmpty == true)
assert(WallaaMokoGATT.telemetryReply(Data([0xeb,1,0x62,1,100]),command:0x62) == nil)
print("4 verifiche telemetria superate")

assert(WallaaMokoGATT.telemetryReply(Data([0xeb,0,0x4f,1,1]),command:0x4f)?["threeAxisAvailable"] as? Bool == true)
assert(WallaaMokoGATT.telemetryReply(Data([0xeb,0,0x4f,2,0,0]),command:0x4f)?["threeAxisAvailable"] as? Bool == false)
assert(WallaaMokoGATT.acceleration(Data([0xeb,2,1,6,0,24,0xff,0x18,3,0xe0]))?["x"] == 24)
assert(WallaaMokoGATT.acceleration(Data([0xeb,2,1,6,0,24,0xff,0x18,3,0xe0]))?["y"] == -232)
assert(WallaaMokoGATT.acceleration(Data([0xeb,2,1,6,0,24,0xff,0x18,3,0xe0]))?["z"] == 992)
assert(WallaaMokoGATT.acceleration(Data([0xeb,2,1,5,0,24,0xff,0x18,3,0xe0])) == nil)
print("6 verifiche capacità H1 e accelerometro superate")

assert(WallaaMokoGATT.accelerationDelta(["x":0,"y":0,"z":1000],["x":160,"y":10,"z":980])==160)
assert(WallaaMokoGATT.accelerationDelta(["x":0,"y":0,"z":1000],["x":10,"y":10,"z":990])==10)

assert(WallaaMokoGATT.shouldPauseCommunity(statusCode:401))
assert(!WallaaMokoGATT.shouldPauseCommunity(statusCode:403))
assert(!WallaaMokoGATT.shouldPauseCommunity(statusCode:503))
assert(WallaaMokoGATT.communityRetryDelay(statusCode:403)==60)
print("4 verifiche recupero ricevitore superate")

assert(WallaaMokoGATT.observationInterval(moving:true)==15)
assert(WallaaMokoGATT.observationInterval(moving:false)==45)
assert(WallaaMokoGATT.observationInterval(moving:nil)==30)
assert(WallaaMokoGATT.movementFlag(Data([0x20,0,0,0,0,0,1,0,1]))==true)
assert(WallaaMokoGATT.movementFlag(Data([0x20,0,0,0,0,0,1,0,0]))==false)
assert(WallaaMokoGATT.movementFlag(Data([0x20,0,0,0]))==nil)
print("6 verifiche ritmo basato sul movimento superate")

let stationary = ["x":8,"y":-40,"z":1012]
let jitter = [["x":4,"y":-40,"z":1012],stationary,["x":8,"y":-36,"z":1016],stationary,stationary]
assert(WallaaMokoGATT.medianAcceleration(jitter) == stationary)
let spike = [stationary,stationary,["x":300,"y":-40,"z":1012],stationary,stationary]
assert(WallaaMokoGATT.medianAcceleration(spike) == stationary)
let shifted = ["x":180,"y":-40,"z":1012]
assert(WallaaMokoGATT.medianAcceleration([stationary,stationary,shifted,shifted,shifted]) == shifted)
assert(WallaaMokoGATT.medianAcceleration([stationary,stationary]) == nil)
print("4 verifiche rumore del sensore e movimento reale superate")
