import {useEffect,useState} from 'react';
import {ArrowLeft,Check,ChevronRight,HeartPulse,LoaderCircle,Mail,Moon,ShieldCheck,Timer,TriangleAlert} from 'lucide-react';
import {uiText as u,uiLocale} from '../uiText';
export default function HealthCheckScreen({health,profile={},onBack,onOpenSOS}){
 const data=health.data||{},settings=data.settings||{},cycle=data.cycle;const isPro=profile.plan==='pro';
 const[duration,setDuration]=useState(settings.thresholdMinutes||30),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[night,setNight]=useState({...{enabled:false,start:'23:00',end:'07:00',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Rome'},...settings.nightMode}),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0);
 useEffect(()=>{setDuration(settings.thresholdMinutes||30);},[settings.thresholdMinutes]);
 useEffect(()=>{if(settings.nightMode)setNight(settings.nightMode);},[settings.nightMode?.enabled,settings.nightMode?.start,settings.nightMode?.end,settings.nightMode?.timeZone]);
 useEffect(()=>{if(data.serverTime)setOffset(new Date(data.serverTime).getTime()-Date.now());},[data.serverTime]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const emailStage=['email_pending','email_sent','email_no_recipients'].includes(cycle?.status);const pending=!data.nightModeActive&&['pending','escalating','email_pending','email_sent','email_no_recipients'].includes(cycle?.status);const needsConsent=settings.needsConsent===true;const consentText='Acconsento espressamente al trattamento dei dati di movimento e delle mie risposte per Health Check, come descritto nell’informativa. Dopo tre avvisi, se non rispondo entro 15 minuti dal primo, Wallaa invia solo un’email ai Guardian Pro configurati con email e avvisi abilitati. La mancata conferma non avvia un SOS. Ho compreso che un pulsante fermo non dimostra un malessere.';const remaining=Math.max(0,Math.ceil((new Date(cycle?.deadlineAt||0).getTime()-now-offset)/1000));const countdown=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;
 const run=async(action)=>{if(busy)return;setBusy(true);setMessage('');try{await action();}catch(e){setMessage(u(e.message));}finally{setBusy(false);}};
 const paused=data.nightModeActive===true;
 return <div className={`screen health-check-screen ${pending?'health-waiting':''}`}>
  <header className="health-heading"><button type="button" onClick={onBack} aria-label={u('Indietro')}><ArrowLeft size={20}/></button><div><small>WALLAA SAFETY</small><h1>Health Check</h1></div><span className="health-pro-label">PRO</span></header>
  <section className="health-visual"><div className="health-ring ring-a"/><div className="health-ring ring-b"/><div className="health-core"><HeartPulse size={46}/></div><span>{pending?u('Verifica in attesa'):paused?'Night Mode':settings.enabled?u('Controllo del movimento'):u('Una conferma, quando serve')}</span></section>
  {pending?<section className="health-question"><span className="health-eyebrow">WALLAA HEALTH CHECK</span><h2>{u('Tutto bene?')}</h2><p>{u('Il Wallaa Button non ha rilevato movimenti per {minutes} minuti.',{minutes:settings.thresholdMinutes||30})}</p><div className="health-deadline"><Mail size={19}/><span>{cycle?.status==='email_sent'?u('Email inviata ai Guardian Pro'):cycle?.status==='email_no_recipients'?u('Nessun Guardian Pro con email disponibile'):cycle?.status==='email_pending'?u('Invio email ai Guardian Pro in corso…'):u('Email ai Guardian Pro tra')}</span>{!emailStage&&<strong>{countdown}</strong>}</div><p className="health-note">{u('La mancata conferma non avvia un SOS e non condivide la posizione.')}</p><div className="health-stages" aria-label={u('Promemoria')}>{[1,2,3].map(stage=><span key={stage} className={stage<=(cycle.stage||1)?'done':''}>{stage}</span>)}</div><div className="health-answer-actions"><button type="button" className="health-answer-well" disabled={busy||cycle.status==='escalating'} onClick={()=>run(()=>health.answer('well'))}><Check size={22}/>{u('Sì, sto bene')}</button><button type="button" className="health-answer-help" disabled={busy||cycle.status==='escalating'} onClick={()=>run(()=>health.answer('help'))}><TriangleAlert size={22}/>{u('No, ho bisogno di aiuto')}</button></div><p className="health-note">{u('Un nuovo movimento del WB-001 chiude automaticamente il controllo.')}</p>{cycle.status==='escalating'&&<p role="status">{u('Avvio SOS in corso…')}</p>}</section>:
   cycle?.status==='sos_sent'&&data.activeSOS?<section className="health-question"><TriangleAlert size={34}/><h2>{u('SOS avviato')}</h2><p>{u('Apri la richiesta per seguire lo stato dell’SOS.')}</p><button type="button" className="health-save" onClick={onOpenSOS}>{u('Apri SOS')}<ChevronRight size={18}/></button></section>:<>
    {['movement','confirmed'].includes(cycle?.status)&&<div className="health-confirmed" role="status"><ShieldCheck size={21}/><span>{cycle.status==='movement'?u('Movimento rilevato: controllo chiuso.'):u('Hai confermato che stai bene.')}<small>{u('Il conteggio riparte da zero.')}</small></span></div>}
    {needsConsent&&<p className="health-note">{u('Health Check è in pausa: conferma il nuovo comportamento con solo email ai Guardian Pro.')}</p>}
    {needsConsent&&settings.enabled&&<button type="button" className="health-verify" disabled={busy} onClick={()=>run(()=>health.save({enabled:false}))}>{u('Disattiva Health Check')}</button>}
    {!isPro&&<div className="health-locked"><ShieldCheck size={25}/><h2>{u('Disponibile con Wallaa Pro')}</h2><p>{u('Health Check usa il sensore del WB-001 per chiederti una conferma dopo un periodo senza movimento.')}</p></div>}
    <section className="health-settings-card"><div className="health-setting-title"><HeartPulse size={22}/><div><h2>{u('Controllo del movimento')}</h2><p>{u('Il controllo riguarda il pulsante, non misura le tue condizioni fisiche.')}</p></div></div><label className="health-duration"><span>{u('Tempo senza movimento')}</span><select value={duration} disabled={!isPro||busy} onChange={e=>setDuration(Number(e.target.value))}>{[[15,u('15 minuti')],[30,u('30 minuti')],[60,u('1 ora')],[120,u('2 ore')]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
     <div className={`health-sensor-status ${data.sensor?.fresh||health.proof?.available?'ready':''}`}><ShieldCheck size={19}/><span>{data.sensor?.fresh||health.proof?.available?u('Sensore di movimento verificato'):u('Sensore da verificare')}</span></div>
     {(!settings.enabled||needsConsent)&&<button type="button" className="health-verify" disabled={!isPro||busy||health.checking} onClick={()=>run(health.verify)}>{health.checking?<LoaderCircle size={17} className="spin"/>:<ShieldCheck size={17}/>} {health.checking?u('Verifica sensore…'):u('Verifica sensore')}</button>}
     {(!settings.enabled||needsConsent)&&isPro&&<label className="health-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{u(consentText)}</span></label>}
     <button type="button" className="health-save" disabled={(!isPro&&!settings.enabled)||busy||((!settings.enabled||needsConsent)&&(!consent||!health.proof?.available))} onClick={()=>run(()=>health.save({enabled:needsConsent?true:!settings.enabled,thresholdMinutes:duration,consentAccepted:consent}))}>{needsConsent?u('Conferma Health Check'):settings.enabled?u('Disattiva Health Check'):u('Attiva Health Check')}</button>
     {settings.enabled&&!needsConsent&&duration!==settings.thresholdMinutes&&<button type="button" className="health-verify" disabled={busy} onClick={()=>run(()=>health.save({enabled:true,thresholdMinutes:duration}))}>{u('Salva durata')}</button>}
     <p className="health-note">{u('Bluetooth, notifiche e collegamento al WB-001 devono essere disponibili. La mancanza di dati non viene contata come immobilità.')}</p>
    </section>
    {(isPro||settings.enabled)&&!needsConsent&&<section className={`health-settings-card health-night-card ${paused?'active':''}`}><div className="health-setting-title"><Moon size={23}/><div><h2>Night Mode</h2><p>{u('Scegli la fascia oraria quotidiana in cui Health Check resta sospeso. Il pulsante SOS rimane attivo.')}</p></div></div>
     <label className="health-night-toggle"><span>{u('Attiva Night Mode')}</span><input type="checkbox" role="switch" checked={night.enabled} disabled={busy||!isPro} onChange={e=>setNight({...night,enabled:e.target.checked})}/></label>
     <div className="health-night-times"><label><span>{u('Dalle')}</span><input type="time" aria-label={u('Inizio Night Mode')} value={night.start} disabled={busy||!isPro} onChange={e=>setNight({...night,start:e.target.value})}/></label><label><span>{u('Alle')}</span><input type="time" aria-label={u('Fine Night Mode')} value={night.end} disabled={busy||!isPro} onChange={e=>setNight({...night,end:e.target.value})}/></label></div>
     {night.enabled&&night.start===night.end&&<p className="health-error" role="alert">{u('Inizio e fine di Night Mode devono essere diversi.')}</p>}
     <p className="health-note">{u('Ogni giorno, anche quando la fascia attraversa la mezzanotte. Alla fine il conteggio riparte da zero con nuovi dati del pulsante.')}</p>
     <p className="health-note">{u('Fuso orario')}: {night.timeZone}</p>
     {paused&&<p className="health-night-status" role="status"><Moon size={18}/>{u('Night Mode attivo: Health Check sospeso')}</p>}
     <button type="button" className="health-verify" disabled={busy||!isPro||(night.enabled&&(!night.start||!night.end||night.start===night.end))} onClick={()=>run(()=>health.save({nightMode:{...night,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||night.timeZone},pausedUntil:null}))}>{u('Salva Night Mode')}</button>
    </section>}
   </>}
  {(message||health.error)&&<p className="health-error" role="alert">{message||u(health.error)}</p>}
  {busy&&<p className="health-progress" role="status"><LoaderCircle size={17} className="spin"/>{u('Aggiornamento in corso…')}</p>}
 </div>;
}
