import { useMemo, useState } from 'react';
import { ChevronRight, Plus, QrCode, RefreshCw, ScanLine, Shield, ShieldCheck, UserRound, X } from 'lucide-react';
import {uiText as u} from '../uiText';
import {safetyPeople} from '../services/safetyNetwork';

function NetworkScene({count}){
 return <div className="safety-scene" aria-hidden="true"><div className="safety-orbit orbit-one"/><div className="safety-orbit orbit-two"/><div className="safety-core"><Shield/><span>W</span></div>{[0,1,2].map((n)=><div key={n} className={`safety-figure figure-${n}`}><div className="figure-aura"/><i className="figure-head"/><i className="figure-body"/><span>{n===0?'W':n===1?'W':'G'}</span></div>)}<div className="safety-scene-caption">{count?u('La tua rete, sempre con te'):u('La sicurezza inizia dalle persone')}</div></div>;
}
export default function NetworkScreen({profile={},contacts=[],networkState={},qrDataUrl,onScan,onRotate,onRemoveLink,onRefresh,onAdd,onEdit,onGuardianSettings}){
 const[showQr,setShowQr]=useState(false);const[details,setDetails]=useState(null);const people=useMemo(()=>safetyPeople(contacts,networkState),[contacts,networkState]);
 const ready=networkState.status==='ready';
 return <div className="screen safety-network-screen">
  <header className="safety-heading"><div><span>WALLAA CONNECT</span><h1>{u('Rete di Sicurezza')}</h1><p>{u('Le persone su cui puoi contare, in un unico posto.')}</p></div><button type="button" onClick={onRefresh} aria-label={u('Aggiorna rete')}><RefreshCw size={19}/></button></header>
  <section className="safety-hero"><NetworkScene count={people.length}/><div className="safety-hero-summary"><span><strong>{people.length}</strong>{u('Persone nella tua rete')}</span><span><ShieldCheck size={16}/>{u('Posizione condivisa durante un SOS')}</span></div></section>
  <div className="safety-add-actions"><button type="button" className="safety-primary" onClick={onAdd}><Plus size={19}/>{u('Aggiungi persona')}</button><button type="button" onClick={onScan} disabled={!ready}><ScanLine size={18}/>{u('Scansiona QR')}</button><button type="button" onClick={()=>setShowQr(!showQr)} aria-expanded={showQr} aria-label={u('Il mio QR')}><QrCode size={20}/></button></div>
  {!ready&&<p className="safety-status" role="status">{u('Rete da aggiornare. Controlla la connessione e riprova.')}</p>}
  {showQr&&<section className="safety-qr-panel"><div><strong>{u('Il mio QR')}</strong><p>{u('Una scansione vi collega: ora vi proteggete a vicenda.')}</p><small>{networkState.customerId||profile.customerId||''}</small><button type="button" onClick={onRotate} disabled={!ready}>{u('Rigenera QR')}</button></div>{qrDataUrl&&<img src={qrDataUrl} alt={u('Il mio QR')}/>}</section>}
  <div className="safety-list-title"><h2>{u('Le tue persone')}</h2><span>{u('W = usa Wallaa')}</span></div>
  <div className="safety-people">{people.map((person,index)=><article key={person.key} className="safety-person" style={{'--arrival':`${index*70}ms`}}><button type="button" className="safety-person-main" onClick={()=>person.id?onEdit(person):person.guardianLinkId?onEdit({...person,linkId:person.guardianLinkId}):setDetails(person)}><span className={`safety-avatar ${person.isWallaa?'wallaa':''}`}><UserRound size={25}/>{person.isWallaa&&<i>W</i>}</span><span className="safety-person-copy"><strong>{person.name}</strong><small>{person.isWallaa?'W Guardian': 'Guardian'}{person.role==='guardian_pro'?' Pro':person.role==='primary'?` · ${u('Principale')}`:''}</small><em>{person.receives&&person.protects?u('Vi proteggete a vicenda'):person.receives?u('Riceve i tuoi SOS'):u('Ricevi i suoi SOS')}</em></span><ChevronRight size={18}/></button>{!person.isWallaa&&!person.email&&<p className="safety-person-note">{u('Aggiungi un’email per ricevere gli avvisi senza Wallaa.')}</p>}{!person.id&&person.guardianLinkId&&<button className="safety-link-remove" type="button" onClick={()=>onRemoveLink(person.guardianLinkId)}>{u('Rimuovi collegamento')}</button>}</article>)}</div>
  {!people.length&&<div className="safety-empty"><ShieldCheck size={30}/><h2>{u('Costruisci la tua rete')}</h2><p>{u('Aggiungi una persona tramite telefono, email, codice cliente o QR.')}</p></div>}
  {details&&<section className="safety-qr-panel" role="region" aria-label={details.name}><div><strong>{details.name}</strong><p>{u('Ricevi i suoi SOS')}</p><p>{u('Questa persona ha scelto di avvisarti. I suoi permessi sono gestiti dal suo account.')}</p><button type="button" onClick={()=>{onRemoveLink(details.followingLinkId);setDetails(null);}}>{u('Smetti di ricevere i suoi SOS')}</button><button type="button" onClick={()=>setDetails(null)}>{u('Chiudi')}</button></div></section>}
  <button type="button" className="safety-options" onClick={onGuardianSettings}><ShieldCheck size={20}/><span><strong>{u('Impostazioni di protezione')}</strong><small>{u('Permessi e protezione durante l’SOS')}</small></span><ChevronRight size={18}/></button>
 </div>;
}
