import {uiText,uiLocale} from '../uiText.js';
import { useMemo, useState } from 'react';
import { ArrowLeft, Camera, Check, FileCheck2, IdCard, ShieldCheck, UserRound } from 'lucide-react';
import { PHONE_COUNTRIES } from '../data/phoneCountries';
import { applyAsSentinel } from '../services/sentinel';

function DocumentGuide({side='front'}){return <div className={`sentinel-id-guide ${side}`}><div className="sentinel-id-paper"><i/><span/><span/><span/>{side==='back'&&<b/>}</div></div>;}
function SelfieGuide(){return <div className="sentinel-selfie-guide"><div className="sentinel-guide-face"><i/><b/></div><div className="sentinel-guide-card"><i/><span/><span/></div><div className="sentinel-guide-fingers">2</div></div>;}
function UploadCard({kind,title,subtitle,file,onFile,required=true,capture='environment'}){return <label className={`sentinel-upload-card ${file?'ready':''}`}>{kind==='selfie'?<SelfieGuide/>:<DocumentGuide side={kind}/>}<div className="sentinel-upload-text"><strong>{title}</strong><span>{subtitle}</span><small>{file?`✓ ${file.name}`:required?'OBBLIGATORIO':'SE PREVISTO'}</small></div><div className="sentinel-upload-button">{file?<Check size={18}/>:<Camera size={18}/>}<span>{file?uiText("Cambia"):uiText("Scatta / carica")}</span></div><input type="file" accept="image/jpeg,image/png,image/heic,image/heif" capture={capture} onChange={(e)=>onFile(e.target.files?.[0]||null)}/></label>;}

export default function SentinelApplicationScreen({networkIdentity,profile,onBack,onSubmitted,setToast}){
 const challengeCode=useMemo(()=>String(1+Math.floor(Math.random()*5)),[]);
 const[step,setStep]=useState(1),[busy,setBusy]=useState(false);
 const[form,setForm]=useState({documentType:'identity_card',documentCountry:profile?.birthCountry||'Italy',documentExpiry:'',documentFront:null,documentBack:null,selfieDocument:null,identityDeclaration:false,sentinelTermsAccepted:false,privacyNoticeAccepted:false});
 const set=(key,value)=>setForm(v=>({...v,[key]:value}));
 const profileComplete=Boolean(profile?.firstName&&profile?.lastName&&profile?.dateOfBirth&&profile?.birthCountry&&profile?.birthPlace&&profile?.email&&profile?.phone);
 const documentReady=Boolean(form.documentCountry&&form.documentExpiry&&form.documentFront&&(form.documentType!=='identity_card'||form.documentBack));
 const legalReady=form.identityDeclaration&&form.sentinelTermsAccepted&&form.privacyNoticeAccepted;
 async function submit(){setBusy(true);try{await applyAsSentinel(networkIdentity,{...form,challengeCode,sentinelTermsVersion:'1.3',privacyNoticeVersion:'1.3'});setToast?.({type:'success',text:uiText("Candidatura Sentinel inviata.")});await onSubmitted?.();}catch(error){setToast?.({type:'error',text:error.message});}finally{setBusy(false);}}
 return <section className="sentinel-application-page">
  <div className="sentinel-application-top"><button onClick={onBack}><ArrowLeft/></button><div><small>WALLAA SENTINEL</small><strong>{"" + uiText("Verifica identità") + ""}</strong></div><ShieldCheck/></div>
  <div className="sentinel-application-progress">{[1,2,3,4].map(n=><span key={n} className={step>=n?'active':''}>{step>n?<Check size={13}/>:n}</span>)}</div>
  {step===1&&<div className="sentinel-application-card"><div className="sentinel-application-icon"><UserRound/></div><small>{"" + uiText("PASSAGGIO 1 DI 4") + ""}</small><h1>{"" + uiText("Controlla i tuoi dati") + ""}</h1><p>{"" + uiText("I dati Wallaa devono corrispondere al documento.") + ""}</p><div className="sentinel-identity-summary"><div><span>{"" + uiText("Nome") + ""}</span><b>{profile?.firstName||'—'} {profile?.lastName||''}</b></div><div><span>{"" + uiText("Data di nascita") + ""}</span><b>{profile?.dateOfBirth||'—'}</b></div><div><span>{"" + uiText("Paese di nascita") + ""}</span><b>{profile?.birthCountry||'—'}</b></div><div><span>{"" + uiText("Luogo di nascita") + ""}</span><b>{profile?.birthPlace||'—'}</b></div></div>{!profileComplete&&<div className="sentinel-form-warning">{"" + uiText("Completa prima tutti i dati del profilo nelle Impostazioni.") + ""}</div>}<button className="sentinel-application-primary" disabled={!profileComplete} onClick={()=>setStep(2)}>{"" + uiText("Continua") + ""}</button></div>}
  {step===2&&<div className="sentinel-application-card"><div className="sentinel-application-icon"><IdCard/></div><small>{"" + uiText("PASSAGGIO 2 DI 4") + ""}</small><h1>{"" + uiText("Documento di identità") + ""}</h1><p>{"" + uiText("Documento intero, nitido, valido e senza riflessi.") + ""}</p><div className="sentinel-form-grid"><label><span>{"" + uiText("Tipo documento") + ""}</span><select value={form.documentType} onChange={(e)=>set('documentType',e.target.value)}><option value="identity_card">{"" + uiText("Carta d'identità") + ""}</option><option value="passport">{"" + uiText("Passaporto") + ""}</option><option value="driving_licence">{"" + uiText("Patente") + ""}</option></select></label><label><span>{"" + uiText("Paese di emissione") + ""}</span><select value={form.documentCountry} onChange={(e)=>set('documentCountry',e.target.value)}><option value="">{"" + uiText("Seleziona Paese") + ""}</option>{PHONE_COUNTRIES.map(c=><option key={c.iso} value={c.name}>{c.flag} {c.name}</option>)}</select></label><label className="wide"><span>{"" + uiText("Scadenza documento") + ""}</span><input type="date" value={form.documentExpiry} onChange={(e)=>set('documentExpiry',e.target.value)}/></label></div><UploadCard kind="front" title={uiText("Fronte documento")} subtitle="Tutti i bordi visibili, testo leggibile." file={form.documentFront} onFile={(f)=>set('documentFront',f)}/>{form.documentType!=='passport'&&<UploadCard kind="back" title={uiText("Retro documento")} subtitle="Fotografa tutto il retro." file={form.documentBack} required={form.documentType==='identity_card'} onFile={(f)=>set('documentBack',f)}/>}<div className="sentinel-application-actions"><button onClick={()=>setStep(1)}>{"" + uiText("Indietro") + ""}</button><button className="primary" disabled={!documentReady} onClick={()=>setStep(3)}>{"" + uiText("Continua") + ""}</button></div></div>}
  {step===3&&<div className="sentinel-application-card"><div className="sentinel-application-icon"><Camera/></div><small>{"" + uiText("PASSAGGIO 3 DI 4") + ""}</small><h1>{"" + uiText("Selfie con documento") + ""}</h1><p>{"" + uiText("Volto e documento devono essere visibili nella stessa foto.") + ""}</p><div className="sentinel-challenge"><SelfieGuide/><div><small>{"" + uiText("VERIFICA VISIVA") + ""}</small><strong>{"" + uiText("Mostra") + " "}{challengeCode}{" " + uiText("dita con la mano libera") + ""}</strong><span>{"" + uiText("Verifica manuale Wallaa. Nessun riconoscimento facciale automatico.") + ""}</span></div></div><UploadCard kind="selfie" capture="user" title={uiText("Selfie + documento")} subtitle={uiText("Mostra volto, documento e {value0} dita.",{value0:(challengeCode)})} file={form.selfieDocument} onFile={(f)=>set('selfieDocument',f)}/><div className="sentinel-photo-rules"><span>{"" + uiText("✓ Buona luce") + ""}</span><span>{"" + uiText("✓ Volto visibile") + ""}</span><span>{"" + uiText("✓ Documento vicino al viso") + ""}</span><span>{"" + uiText("✕ Niente occhiali scuri") + ""}</span><span>{"" + uiText("✕ Niente foto di schermi") + ""}</span><span>{"" + uiText("✕ Niente documento tagliato") + ""}</span></div><div className="sentinel-application-actions"><button onClick={()=>setStep(2)}>{"" + uiText("Indietro") + ""}</button><button className="primary" disabled={!form.selfieDocument} onClick={()=>setStep(4)}>{"" + uiText("Continua") + ""}</button></div></div>}
  {step===4&&<div className="sentinel-application-card"><div className="sentinel-application-icon"><FileCheck2/></div><small>{"" + uiText("PASSAGGIO 4 DI 4") + ""}</small><h1>{"" + uiText("Conferma e invia") + ""}</h1><p>{"" + uiText("Wallaa controllerà manualmente la candidatura.") + ""}</p><div className="sentinel-consents"><label><input type="checkbox" checked={form.identityDeclaration} onChange={(e)=>set('identityDeclaration',e.target.checked)}/><span>{"" + uiText("Confermo che dati, documento e fotografie appartengono a me e sono veritieri.") + ""}</span></label><label><input type="checkbox" checked={form.sentinelTermsAccepted} onChange={(e)=>set('sentinelTermsAccepted',e.target.checked)}/><span>{"" + uiText("Accetto le Condizioni Wallaa Sentinel e confermo di avere almeno 18 anni.") + ""}</span></label><label><input type="checkbox" checked={form.privacyNoticeAccepted} onChange={(e)=>set('privacyNoticeAccepted',e.target.checked)}/><span>{"" + uiText("Dichiaro di aver letto l'informativa privacy della verifica Sentinel.") + ""}</span></label></div><div className="sentinel-privacy-note"><ShieldCheck size={18}/><p>{"" + uiText("Documento e selfie sono usati per la verifica manuale e non vengono pubblicati.") + ""}</p></div><div className="sentinel-application-actions"><button disabled={busy} onClick={()=>setStep(3)}>{"" + uiText("Indietro") + ""}</button><button className="primary" disabled={!legalReady||busy} onClick={submit}>{busy?uiText("Invio in corso…"):uiText("Invia candidatura")}</button></div></div>}

        {/* WALLAA_SENTINEL_LEGAL_LINKS_V1_1 */}
        <div className="sentinel-legal-doc-links">
          <a href="https://wallaasafety.com/legal/wallaa-sentinel-terms-1.3-2026-10-09.pdf" target="_blank" rel="noreferrer">{"" + uiText("Apri Termini Sentinel v1.3") + ""}</a>
          <a href="https://wallaasafety.com/legal/wallaa-sentinel-privacy-notice-1.3-2026-10-09.pdf" target="_blank" rel="noreferrer">{"" + uiText("Apri Sentinel Privacy Notice v1.3") + ""}</a>
          <a href="https://wallaasafety.com/legal/wallaa-safety-notice-2.3-2026-10-09.pdf" target="_blank" rel="noreferrer">{"" + uiText("Apri Safety Notice v2.1") + ""}</a>
        </div>
</section>;
}
