import {test,expect} from '@playwright/test';
test('MK1 explains its SOS command without a gesture selector',async({page})=>{await page.goto('/tests/ui/index.html?screen=device');await expect(page.locator('.aa-trigger-list button')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Premi per inviare SOS'})).toBeVisible();});
test('button has a single SOS explanation without gesture choices',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&legacy');await expect(page.locator('.aa-trigger-list button')).toHaveCount(0);});
test('incomplete setup is recoverable and not shown connected',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&incomplete');await expect(page.getByRole('button',{name:'Completa collegamento'})).toBeVisible();await expect(page.getByText('Da configurare',{exact:true})).toBeVisible();});
test('physical proof has explicit no-SOS instructions and can be cancelled',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&empty&state=awaiting_press');await expect(page.getByRole('status')).toContainText('Questa prova non invia SOS');await expect(page.getByRole('button',{name:'Annulla collegamento'})).toBeVisible();await expect(page.getByRole('button',{name:'Ricerca e associazione…'})).toBeDisabled();});

test('old MK1 without a MAC still has one gesture and a recovery action',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&unidentified');await expect(page.locator('.aa-trigger-list button')).toHaveCount(0);await expect(page.getByRole('button',{name:'Completa collegamento'})).toBeVisible();await expect(page.getByText('Associato al tuo account',{exact:true})).toHaveCount(0);});
test('idle pairing does not claim success before verification',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&empty');await expect(page.getByText('Dispositivo collegato con successo',{exact:true})).toHaveCount(0);});

test('generic legacy ownership is not presented as a verified MK1',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&legacyHash');await expect(page.getByRole('button',{name:'Completa collegamento'})).toBeVisible();await expect(page.getByText('Da configurare',{exact:true})).toBeVisible();await expect(page.getByText('Associato al tuo account',{exact:true})).toHaveCount(0);});

test('tapping a discovered device advances the recovery screen',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&legacyHash&state=selecting');await page.getByRole('button',{name:/Pulsante vicino · 9F8B/}).tap();await expect(page.getByRole('status')).toContainText('Collegamento al pulsante');await expect(page.locator('.mk1-candidates')).toHaveCount(0);});

test('setup failure remains visible beside the recovery action',async({page})=>{await page.goto('/tests/ui/index.html?screen=device&legacyHash&setupError');await expect(page.getByRole('alert')).toContainText('Collegamento non riuscito');await expect(page.getByRole('button',{name:'Completa collegamento'})).toBeVisible();});
