import {useState} from 'react';
import {ShieldCheck,MapPin,Bluetooth,Bell,Check,ArrowRight,Settings} from 'lucide-react';
export default function SafetyPermissionGuide({status={},onActivate,onRefresh,onFinish,onSettings}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ready=status.location==='always'&&status.notifications&&status.bluetooth;
 async function activate(){setBusy(true);setError('');try{await onActivate?.();}catch(e){setError(e.message||'Non è stato possibile completare la richiesta.');}finally{setBusy(false);}}
 const rows=[[MapPin,'Posizione anche in background','Aiuta Wallaa ad aggiungere la tua posizione all’SOS quando l’iPhone è bloccato.',status.location==='always'],[Bluetooth,'WB-001 e Bluetooth','Riceve la pressione del tuo pulsante.',status.bluetooth],[Bell,'Notifiche di sicurezza','Ricevi richieste, avvisi e aggiornamenti.',status.notifications]];
 return <div className="safety-guide-backdrop"><section className="safety-guide" role="dialog" aria-modal="true" aria-labelledby="safety-guide-title"><div className="safety-guide-shield"><ShieldCheck/></div><span className="safety-guide-eyebrow">WALLAA · SICUREZZA</span><h2 id="safety-guide-title">Prepariamo la tua protezione</h2><p>La posizione in background è importante per condividere informazioni utili quando chiedi aiuto. iOS richiede la tua autorizzazione: scegli <b>Sempre</b> nella richiesta di posizione.</p><div className="safety-guide-steps">{rows.map(([Icon,title,body,ok])=><div key={title} className={ok?'done':''}><Icon/><span><strong>{title}</strong><small>{body}</small></span>{ok?<Check/>:<span className="safety-guide-pending">Da attivare</span>}</div>)}</div><div className="safety-guide-privacy"><ShieldCheck/><p>La tua posizione non è pubblica. Durante un SOS viene condivisa con i contatti autorizzati e la Centrale. Con Guardian Mode attiva, la condivisione autorizzata può proseguire anche fuori dall’SOS. La rete Wallaa può usare zone approssimative per ritrovare i pulsanti.</p></div>{status.backgroundRefresh===false&&<p className="safety-guide-warning">iOS segnala l’aggiornamento in background non disponibile{status.lowPower?' con il risparmio energetico attivo':''}. Questa impostazione di sistema si gestisce dall’iPhone.</p>}{error&&<p role="alert">{error}</p>}<div className="safety-guide-controls"><button type="button" className="safety-guide-primary" disabled={busy} onClick={ready?onFinish:activate}>{busy?'Richiesta in corso…':ready?'Protezione configurata':'Attiva i permessi'}<ArrowRight/></button><div className="safety-guide-actions"><button onClick={onRefresh} type="button">Verifica stato</button><button onClick={onSettings} type="button"><Settings/>Impostazioni iPhone</button></div>{!ready&&<button type="button" className="safety-guide-later" onClick={onFinish}>Completerò dopo · alcune funzioni saranno limitate</button>}</div></section></div>;
}
