import {uiText,uiLocale} from '../uiText.js';
import {useState} from 'react';
import {ShieldCheck,MapPin,Bluetooth,Bell,Check,ArrowRight,Settings} from 'lucide-react';
export default function SafetyPermissionGuide({status={},onActivate,onRefresh,onFinish,onSettings}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ready=status.location==='always'&&status.notifications&&status.bluetooth;
 async function activate(){setBusy(true);setError('');try{await onActivate?.();}catch(e){setError(e.message||uiText("Non è stato possibile completare la richiesta."));}finally{setBusy(false);}}
 const rows=[[MapPin,uiText("Posizione anche in background"),uiText("Aiuta Wallaa ad aggiungere la tua posizione all’SOS quando l’iPhone è bloccato."),status.location==='always'],[Bluetooth,uiText("WB-001 e Bluetooth"),uiText("Riceve la pressione del tuo pulsante."),status.bluetooth],[Bell,uiText("Notifiche di sicurezza"),uiText("Ricevi richieste, avvisi e aggiornamenti."),status.notifications]];
 return <div className="safety-guide-backdrop"><section className="safety-guide" role="dialog" aria-modal="true" aria-labelledby="safety-guide-title"><div className="safety-guide-shield"><ShieldCheck/></div><span className="safety-guide-eyebrow">{"" + uiText("WALLAA · SICUREZZA") + ""}</span><h2 id="safety-guide-title">{"" + uiText("Prepariamo la tua protezione") + ""}</h2><p>{"" + uiText("La posizione in background è importante per condividere informazioni utili quando chiedi aiuto. iOS richiede la tua autorizzazione: scegli") + " "}<b>{"" + uiText("Sempre") + ""}</b>{" " + uiText("nella richiesta di posizione.") + ""}</p><div className="safety-guide-steps">{rows.map(([Icon,title,body,ok])=><div key={title} className={ok?'done':''}><Icon/><span><strong>{title}</strong><small>{body}</small></span>{ok?<Check/>:<span className="safety-guide-pending">{"" + uiText("Da attivare") + ""}</span>}</div>)}</div><div className="safety-guide-privacy"><ShieldCheck/><p>{"" + uiText("La tua posizione non è pubblica. I Guardian autorizzati possono seguirla solo durante un SOS attivo. La Centrale gestisce le informazioni secondo le impostazioni di sicurezza. La rete Wallaa usa zone approssimative per ritrovare i pulsanti.") + ""}</p></div>{status.backgroundRefresh===false&&<p className="safety-guide-warning">{"" + uiText("iOS segnala l’aggiornamento in background non disponibile") + ""}{status.lowPower?' con il risparmio energetico attivo':''}{"" + uiText(". Questa impostazione di sistema si gestisce dall’iPhone.") + ""}</p>}{error&&<p role="alert">{error}</p>}<div className="safety-guide-controls"><button type="button" className="safety-guide-primary" disabled={busy} onClick={ready?onFinish:activate}>{busy?uiText("Richiesta in corso…"):ready?uiText("Protezione configurata"):uiText("Attiva i permessi")}<ArrowRight/></button><div className="safety-guide-actions"><button onClick={onRefresh} type="button">{"" + uiText("Verifica stato") + ""}</button><button onClick={onSettings} type="button"><Settings/>{"" + uiText("Impostazioni iPhone") + ""}</button></div>{!ready&&<button type="button" className="safety-guide-later" onClick={onFinish}>{"" + uiText("Completerò dopo · alcune funzioni saranno limitate") + ""}</button>}</div></section></div>;
}
